services:
  paste-feed-prod:
    image: paste-feed:latest
    build: .
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - ./data:/data
    ports:
      - "8090:8080"
