services:
  paste-feed:
    image: navedrangwala/paste-feed:latest
    restart: unless-stopped
    environment:
      - FEED_DATA_DIR=/data
      - TZ=America/Los_Angeles
    volumes:
      - ./data:/data
    ports:
      - "8090:8080"
