services:
  paste-feed-prod:
    image: paste-feed:latest
    build:
      context: .
      secrets:
        - npmrc
    restart: unless-stopped
    environment:
      - FEED_DATA_DIR=/data
      - TZ=America/Los_Angeles
    volumes:
      - ./data:/data
    ports:
      - "8090:8080"

secrets:
  npmrc:
    file: ${HOME}/.npmrc
